### PR TITLE
[NCL-7445] Always display SSH button on build log page for admin users

### PR DESCRIPTION
**Pull request by DnsZhou**

### CODE REVIEW

**Comment by DnsZhou** [comment]
This PR is on hold due to missing backend support, see NCL-8756.

**Comment by DnsZhou** [comment]
After discussion with Martin, since the missing support from the backend affects only pnc admin user, this jira can still be merged and changes will work immediately when backend support is implemented.

**Comment by DnsZhou** [comment]
Hi @matedo1 , in AngularJs web UI there is no whole screen error messages, just normal backend error warnings(see jira comments). This will disappear automatically when backend changes are made. Can we just keep it like this, and not add a temporary catch to this error?

**Review by matedo1 — APPROVED** [review]
Yes, that's fine, thank you for the clarification.

**Pull request merged**
